optimizer : {
  type: AdamW,
  kwargs: {
  lr : 0.001,
  weight_decay : 0.05
}}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 2000,
    initial_epochs : 10
}}

dataset : {
  train : { _base_: configs/TanksAndTemples.yaml,
            others: {subset: 'train', npoints: 16384}},
  val : { _base_: configs/TanksAndTemples.yaml,
            others: {subset: 'test', npoints: 16384}},
  test : { _base_: configs/TanksAndTemples.yaml,
            others: {subset: 'test', npoints: 16384}}}

model : {
  NAME: Point_MAE,
  group_size: 128,
  num_group: 64,
  loss: cdl2,
  transformer_config: {
    mask_ratio: 0.6,
    mask_type: 'rand',
    trans_dim: 768,
    encoder_dims: 768,
    depth: 12,
    drop_path_rate: 0.1,
    num_heads: 6,
    decoder_depth: 4,
    decoder_num_heads: 6,
    patch_size: 28,
    vit_model_name: 'google/vit-base-patch16-224-in21k'
  },
  }

npoints: 16384
total_bs : 256
step_per_update : 1
max_epoch : 2000